# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

{{- range $pod, $e := until ( .Values.dataNodes | int) }}
{{- range $key, $role := $.Values.postgresql.roles }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "createrole-dn-role-%s-%s-%s" $.Release.Name ($pod | toString) ($key | toString) | trunc 63 }}
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    chart: {{ template "timescaledb.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: {{ template "timescaledb.fullname" $ }}
        chart: {{ template "timescaledb.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
    spec:
      containers:
      - name: createrole-dn-{{ $key }}
        image: postgres:11-alpine # A relatively small official image that can run psql
        command:
          - sh
          - -c
          - >
              while ! pg_isready -U postgres -h "${DATA_NODE_DNS}" ; do sleep 1; done;
              echo "rolename: ${ROLENAME}";
              echo "${SQLCOMMAND}" | psql -U postgres -d "${DATA_NODE_CONNSTR}" --file=- --set ON_ERROR_STOP=1 \
                --set rolename="${ROLENAME}" \
                --set internalpass="${INTERNALPASS}"
        env:
        - name: ROLENAME
          value: {{ $key }}
        - name: INTERNALPASS 
          valueFrom:
            secretKeyRef:
              name: timescaledb-internal-{{ $key }}
              key: password-superuser
        - name: DATA_NODE_DNS
          value: {{ template "timescaledb.dataname" $ }}-{{ $pod }}.{{ template "timescaledb.dataname" $ }}
        - name: DATA_NODE_CONNSTR 
          value: host={{ template "timescaledb.dataname" $ }} user=postgres connect_timeout=3 sslmode=disable
        - name: SQLCOMMAND
          value: |
            CREATE ROLE :rolename PASSWORD :'internalpass' LOGIN;
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "timescaledb.dataname" $ }}
              key: password-superuser
      restartPolicy: OnFailure
  backoffLimit: 10
...
{{ end }}
{{ end }}
